spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-client
server:
  port: 8203
---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-client
server:
  port: 8202